---
- name: import repo
  get_url:
    url: "{{ asterisk_yum_repo_url }}"
    dest: /etc/yum.repos.d/asterisk.repo
    mode: 0640

- name: import gpg key
  rpm_key:
    key: "{{ asterisk_yum_gpg_url }}"
    state: present

- name: enable-repos
  shell: |
    yum-config-manager --enable asterisk-13
    yum-config-manager --enable asterisk-common

- name: enable-path-asterisk-common
  lineinfile:
    dest: /etc/yum.repos.d/asterisk.repo
    regexp: '#baseurl=https:\/\/ast\.tucny\.com\/repo\/asterisk-common\/el\$releasever\/\$basearch\/'
    line: "baseurl=https://ast.tucny.com/repo/asterisk-common/el$releasever/$basearch/"

- name: enable-path-asterisk-13
  lineinfile:
    dest: /etc/yum.repos.d/asterisk.repo
    regexp: '#baseurl=https:\/\/ast\.tucny\.com\/repo\/asterisk-13\/el\$releasever\/\$basearch\/'
    line: "baseurl=https://ast.tucny.com/repo/asterisk-13/el$releasever/$basearch/"

- name: install
  yum:
    name:
      - asterisk
      - asterisk-voicemail-plain
      - asterisk-pjsip
    enablerepo: "{{ asterisk_enablerepo | default(omit, true) }}"

- name: config
  copy:
    src: "{{ item }}"
    dest: "/etc/asterisk/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0640
  with_items: "{{ asterisk_configs | default([]) | list }}"
  notify:
    - systemd asterisk restart

- name: systemd asterisk start enable
  systemd:
    name: asterisk
    state: started
    enabled: yes
  when: ansible_distribution_major_version|int > 6
  tags:
    - asterisk
    - services
